Initial attempt at compiler test framework
pureqml/qmlcore pull request #211
Opened 2021-07-11 04:00 UTC by tomager

This change adds a test framework for the compiler, that is based on the lit tool [4] of clang/llvm that is used for their massive test suite. The sources are copied from the llvm-12 tree and the integration roughly follows [5].

The tests are at `qmlcore/test/qml/*.qml`. The test suite can be run by doing `make` or `make check` from `qmlcore/test`. You can also run `./lit.py . -va` and `./lit.py --help` from the test directory to get verbose and a bunch of other options.

The key benefit of these kinds of tests is that they are really concise and easy to write. I added three test cases, gh172-a, gh172-b, gh205 [1-3]. "gh" stands for github, and the number is the related issue number. Basically the "// RUN: xyz" directives execute shell commands and the test fails if any of the commands fail. The %build and %out are special qmlcore substitutions defined in test/lit.cfg.py (you can see their expansions with ./lit.py -va). So [1] and [2] just verify that compilation fails given the bad input, and [3] verifies that the relevant part of the output js is generated.

All the tests don't have to be written at once-- they can just be accumulated over time as new issues come in and new features are introduced. Having a proper regression test suite is incredibly important for long term maintainability by more people.

Let me know if this approach is agreeable and if so, any changes that need to be made before merge.

[1]
```
// RUN:  !(%build)

Item {
    id: myItem;
    width: x12906efiuh;
}
```

[2]
```
// RUN: !(%build)

Item {
    id: myItem;
    width: x12906efiuh.o9898dsf;
}
```

[3]
```
// RUN: %build
// RUN: grep "delegate.width = (delegate.parent.parent.w0)" %out/web/qml.gh205.js

Item {
    anchors.fill: context;
    property color defaultColor: "blue";
    Rectangle {
        anchors.fill: parent;
        color: parent.defaultColor;
    }

    property int w0: width/5;

    ListView {
        model: ListModel {
            ListElement { value: "foo"; }
            ListElement { value: "bar"; }
            ListElement { value: "baz"; }
        }
        anchors.fill: parent;
        delegate: Rectangle {
            color: defaultColor;
            width: w0;
            height: parent.parent.w0;
            Rectangle {
                anchors.margins: 10;
                anchors.fill: parent;
                color: "red";
                Text {
                    anchors.centerIn: parent;
                    color: "white";
                    text: model.value + " " + w0;
                }
                width: 100;
                height: 100;
            }
        }
    }
}
```

[4] https://llvm.org/docs/CommandGuide/lit.html

[5] https://medium.com/@mshockwave/using-llvm-lit-out-of-tree-5cddada85a78

2021-07-11 18:02 UTC, tomager commented
Looking at this again this morning, I think the new --build-dir option slightly changes the default behavior. Without giving the option, it puts the output in build.web/web.

I'll push a fix to this PR a bit later so that existing behavior does not change.

2021-07-20 16:53 UTC, whoozle requested changes

2021-07-20 16:53 UTC, whoozle commented on build
> +parser.add_argument('--build-dir', default = 'build.%%platform', help = 'build output directory')
can we use jinja like notation for that? {{platform}} maybe?

2021-07-20 16:53 UTC, whoozle commented on build
> +		manifest = mf.load(StringIO(args.inline_manifest))
mf.loads(args.inline_manifest)

2021-07-20 16:53 UTC, whoozle commented on build
> +	build_dir = args.build_dir.replace("%%platform", platform)
{{platform}}

2021-07-20 16:53 UTC, whoozle commented on build
> +parser.add_argument('--inline-manifest', default = None, help = 'manifest given in the option value')
do you use this option in tests? if not, maybe we can just remove the warning about default manifest being used?

2021-07-20 16:53 UTC, whoozle commented on test/lit.py
> +#!/usr/bin/env python
can you add it as submodule?

2021-07-20 16:53 UTC, whoozle commented on build
> +		target = path.join(build_dir, platform, app)
can you use the old behaviour here? many deploy scripts are already using this layout

2021-07-21 16:00 UTC, tomager commented on build
> +parser.add_argument('--build-dir', default = 'build.%%platform', help = 'build output directory')
Okay

2021-07-21 16:01 UTC, tomager commented on build
> +		manifest = mf.load(StringIO(args.inline_manifest))
Okay

2021-07-21 16:01 UTC, tomager commented on build
> +	build_dir = args.build_dir.replace("%%platform", platform)
Okay

2021-07-21 16:03 UTC, tomager commented on build
> +parser.add_argument('--inline-manifest', default = None, help = 'manifest given in the option value')
The lit.cfg.py uses this to achieve the following behavior: since each test is a single qml file and they live in the same directory, each invocation of the compiler is told the exact root qml file and the package name. If you don't like the --inline-manifest way, what about having another option (like --test <qml_file>) that does the same behavior?

From lit.cfg.py, here is how inline manifest is populated:

```
manifest = '{"sources":"qml","apps":["%noext_basename_s"],"package":"test"}'
config.substitutions.append(("%out","%S/../build.%basename_t"))
config.substitutions.append(('%build', ": rm -f %s/test.%%noext_basename_s && rm -rf build.%%basename_t && cd %s && %s -v --build-dir=build.%%basename_t --cache-dir=%s --inline-manifest=\'%s\'" % (cache_dir, config.test_exec_root, build_path, cache_dir, manifest)))

```

2021-07-21 16:04 UTC, tomager commented on test/lit.py
> +#!/usr/bin/env python
Okay. All the other lit code is in the lit subdirectory/submodule, this is the just the main script that the makefile in qmlcore/test invokes. It can be moved into the lit subdirectory/submodule.

2021-07-21 16:05 UTC, tomager commented on build
> +		target = path.join(build_dir, platform, app)
Yes, will fix this, that's the one I mentioned earlier.

2021-07-21 16:42 UTC, whoozle commented on build
> +parser.add_argument('--inline-manifest', default = None, help = 'manifest given in the option value')
ah, I see, I'm fine with new option if you need it!

2021-07-21 16:43 UTC, whoozle commented on test/lit.py
> +#!/usr/bin/env python
ah, sorry for the confusion, I meant that lit code should go to the submodule (ideally unmodified original repo), if you need any qmlcore specific scripts, they they should stay :)

2021-07-21 16:47 UTC, whoozle commented on build
> +		target = path.join(build_dir, platform, app)
Why not just create a function like `replace_vars_in_path` (any name you find suitable really), and do something like 
```python
target = path.join(replace_vars_in_path(args.build_dir, {platform: platform}), app)
```

2021-08-14 14:56 UTC, tomager commented
I pushed fixes for the items mentioned above. Let me know if you want anything else changed before merging.

2021-08-14 19:24 UTC, whoozle commented
I checked out your branch and tried to run the tests:
```
make
-- Testing: 3 tests, 3 workers --
FAIL: Compiler Tests :: qml/gh172-b.qml (1 of 3)
FAIL: Compiler Tests :: qml/gh172-a.qml (2 of 3)
FAIL: Compiler Tests :: qml/gh205.qml (3 of 3)
********************
Failed Tests (3):
  Compiler Tests :: qml/gh172-a.qml
  Compiler Tests :: qml/gh172-b.qml
  Compiler Tests :: qml/gh205.qml


Testing Time: 0.27s
  Failed: 3
make: *** [Makefile:4: check] Error 1
```
is it supposed to be run from the test directory? (no makefile in test/qml)

2021-08-14 19:35 UTC, tomager commented
Hm. Yes, it's supposed to be run from the test directory, and the gh172* tests are supposed to be failing. Why is gh205 failing for you?

Here is what I see:

```
compiler-test-framework/test# make
-- Testing: 3 tests, 3 workers --
FAIL: Compiler Tests :: qml/gh172-a.qml (1 of 3)
FAIL: Compiler Tests :: qml/gh172-b.qml (2 of 3)
PASS: Compiler Tests :: qml/gh205.qml (3 of 3)
********************
Failed Tests (2):
  Compiler Tests :: qml/gh172-a.qml
  Compiler Tests :: qml/gh172-b.qml


Testing Time: 39.13s
  Passed: 1
  Failed: 2
make: *** [Makefile:4: check] Error 1
```

2021-08-14 20:21 UTC, whoozle commented
Have you tried cleaning old test building artefacts? Maybe it's because you changed --build-dir and your old files are still there?

2021-08-14 20:27 UTC, whoozle commented
./lit.py -va qml/

```
copying from /home/megath/projects/pureqml/itvware-gui-2019/app/qmlcore/test/../platform/html5/dist to build.gh205.qml
+ /home/megath/projects/pureqml/itvware-gui-2019/app/qmlcore/test/../platform/html5/dist/index.html
+ /home/megath/projects/pureqml/itvware-gui-2019/app/qmlcore/test/../platform/html5/dist/modernizr-custom.js
grep: /home/megath/projects/pureqml/itvware-gui-2019/app/qmlcore/test/qml/../build.gh205.qml/web/qml.gh205.js: No such file or directory
```

there's no `web/` subfolder in build dir, but it's present in grep command

2021-08-14 20:34 UTC, tomager commented
Yes, that's right-- I had old build artifacts, and the grep relied on the regressed build/platform behavior I fixed in my earlier change today. I pushed a fix for the test now, so you should see 2 fail 1 pass which is the correct/expected result.

2021-08-14 21:26 UTC, whoozle commented
haha, just wanted to ask you about adding `make clean`, but it's working fine! Thank you very much for your work!

2021-08-14 21:27 UTC, merged

2021-08-15 21:16 UTC, whoozle commented
I've added lit tests to github actions, otherwise no one will run them :D

https://github.com/pureqml/qmlcore/actions/workflows/main.yml